package server
const (
	BASE_URL = "http://www.mean101.com/"
	TEMPLATE_ARTICAL              = "/templates/doc.html"
	//BASE_URL                      = "http://localhost:9091/"
	DELIMITER                     = "^^^"
	DESCRIPTION                   = "Go语言，炫酷动画，建站技术，尽在Go+。"
	ERROR_BAD_REQUEST             = "You must provide the certification."
	ERROR_NOT_PERMISSION          = "You don't currently have permission to post this article."
	ERROR_SERVER_INTERNAL         = "Sorry, An internal Server Error occurred."
	ERROR_TEMPLATE_NOT_FOUND      = "The target template file not found!"
	KEYWORD                       = "Go语言，SVG 动画，Canvas 动画，MongoDB，RethinkDB，Node.js,Rust 语言，Python"
	KEY_ADMIN_CERTIFICATION_TOKEN = "admin-account"
	KEY_COLLECTOR                 = "-keycollotor"
	PATH_CACHE                    = "/home/psycho/public/cache/"
	PATH_DB                       = "/home/psycho/db"
	PATH_PUBLIC                   = "/home/psycho/public"
	PATH_STATIC                   = "/home/psycho/public/dist"
	PREFIX_INDEX                  = "index-"
	PREFIX_SCRIPT                 = "index-script-"
	PREFIX_USER                   = "z-user-"
	PREFIX_COMMENT                = "z-comment-"
	TEMPLATE_INDEX                = "/templates/index.html"
	TEMPLATE_LAYOUT               = "/templates/layout.html"
	TITLE                         = "炫酷的网站技术 - GO+"
	EXTENSION_HTML                = ".html"
)
// go run /home/psycho/go/src/web/server/const.go
